if (!IsMounted("left4dead2")) then return end

sound.AddSoundOverrides("lua/l4d2_game_sounds_infected_common.lua")
sound.AddSoundOverrides("lua/l4d2_game_sounds_infected_special.lua")
sound.AddSoundOverrides("lua/l4d2_game_sounds_player.lua")
sound.AddSoundOverrides("lua/l4d2_game_sounds_music.lua")
sound.AddSoundOverrides("lua/l4d2_game_sounds_doors.lua")  
sound.AddSoundOverrides("lua/l4d2_game_sounds_weapons.lua")      
sound.AddSoundOverrides("lua/l4d2_game_sounds_gambler.lua")      
sound.AddSoundOverrides("lua/l4d2_game_sounds_producer.lua")      
sound.AddSoundOverrides("lua/l4d2_game_sounds_coach.lua")      
sound.AddSoundOverrides("lua/l4d2_game_sounds_mechanic.lua")      
sound.AddSoundOverrides("lua/l4d2_game_sounds_namvet.lua")      
sound.AddSoundOverrides("lua/l4d2_game_sounds_teengirl.lua")      
sound.AddSoundOverrides("lua/l4d2_game_sounds_biker.lua")      
sound.AddSoundOverrides("lua/l4d2_game_sounds_manager.lua")      